points_of_interest: null
visibility_type: null
schema: PUBLIC
show_in_getting_started: false
name: PRODUCTS
entity_name: null
display_name: Products
caveats: null
active: true
entity_type: entity/ProductTable
field_order: database
description: This is our product catalog. It includes all products ever sold by the
  Sample Company.
