points_of_interest: null
preview_display: true
values:
  human_readable_values: []
settings: null
fingerprint:
  global:
    distinct-count: 200
    nil%: 0.0
visibility_type: normal
base_type: type/Integer
last_analyzed: '2021-07-05T12:47:42.993538Z'
custom_position: 0
special_type: type/FK
position: 2
fingerprint_version: 5
name: PRODUCT_ID
database_position: 2
has_field_values: null
display_name: Product ID
parent_id: null
caveats: null
active: true
database_type: INTEGER
description: The product ID. This is an internal identifier for the product, NOT the
  SKU.
fk_target_field_id: /databases/Sample Dataset/schemas/PUBLIC/tables/PRODUCTS/fields/ID
