points_of_interest: null
preview_display: true
values:
  human_readable_values: []
settings: null
fingerprint: null
visibility_type: normal
base_type: type/Text
last_analyzed: null
custom_position: 0
special_type: null
position: 9
fingerprint_version: 0
name: location_attribute_type_handler_config
database_position: 9
has_field_values: null
display_name: Location Attribute Type Handler Config
parent_id: null
caveats: null
active: true
database_type: text
description: null
fk_target_field_id: null
