enable-whitelabeling?: null
jwt-enabled: 'false'
ldap-host: null
jwt-attribute-email: null
engines: null
application-colors: '{}'
enable-embedding: 'false'
jwt-shared-secret: null
enable-xrays: 'true'
application-favicon-url: null
ga-code: null
query-caching-max-ttl: '8640000'
saml-keystore-path: null
email-smtp-username: null
slack-token: null
saml-attribute-firstname: null
saml-keystore-password: null
premium-features: null
saml-enabled: 'false'
version-info: '{}'
ldap-sync-user-attributes-blacklist: null
query-caching-max-kb: '1000'
ldap-attribute-email: null
ldap-password: null
jwt-identity-provider-uri: null
saml-group-sync: 'false'
custom-geojson: '{}'
enable-password-login: 'true'
enable-public-sharing: 'false'
redirect-all-requests-to-https: 'false'
enable-query-caching: 'false'
saml-identity-provider-issuer: null
password-complexity: null
email-smtp-port: null
types: null
ldap-port: null
saml-attribute-email: null
humanization-strategy: null
email-from-address: null
check-for-updates: 'true'
send-new-sso-user-admin-email?: 'true'
hide-embed-branding?: null
show-homepage-data: 'true'
breakout-bins-num: '8'
site-name: Metawhat
ssl-certificate-public-key: null
site-url: http://localhost:3000
jwt-group-mappings: '{}'
ldap-bind-dn: null
site-locale: null
saml-group-mappings: '{}'
enable-enhancements?: null
ldap-group-sync: 'false'
enable-sso?: null
report-timezone: null
saml-application-name: null
breakout-bin-width: '10.0'
email-smtp-host: null
ldap-attribute-firstname: null
report-timezone-short: null
email-configured?: null
jwt-attribute-firstname: null
google-auth-auto-create-accounts-domain: null
jwt-attribute-lastname: null
setup-token: null
saml-identity-provider-uri: null
has-sample-dataset?: null
enable-nested-queries: 'true'
ldap-group-mappings: '{}'
ldap-user-base: null
ldap-security: null
ldap-user-filter: null
other-sso-configured?: null
query-caching-min-ttl: '60'
admin-email: null
available-timezones: null
application-name: null
version: null
jwt-group-sync: 'false'
application-logo-url: null
saml-identity-provider-certificate: null
ldap-attribute-lastname: null
query-caching-ttl-ratio: '10'
start-of-week: null
email-smtp-password: null
map-tile-server-url: null
email-smtp-security: none
ldap-group-base: null
show-homepage-xrays: 'true'
landing-page: null
premium-embedding-token: null
enable-audit-app?: null
ldap-sync-user-attributes: 'true'
google-auth-client-id: null
embedding-secret-key: null
custom-formatting: '{}'
ldap-configured?: null
saml-attribute-lastname: null
available-locales: null
jwt-attribute-groups: null
enable-sandboxes?: null
saml-keystore-alias: null
anon-tracking-enabled: 'false'
source-address-header: null
embedding-app-origin: null
ldap-enabled: 'false'
metabot-enabled: 'false'
saml-attribute-group: null
entities: null
